Bugfix/output directories
EBI-Metagenomics/mobilome-annotation-pipeline pull request #42
Opened 2024-12-10 16:38 UTC by Vkale1

Some minor modifications to output directory.

- genomad_out was a nested directory
- ice finder tmp takes up a lot of space and not needed. This is the best solution I could find.. happy if you find a better one!

2024-12-11 09:50 UTC, mberacochea requested changes
Thanks Varsha.. I left a comment with an alternative approach to the deletion of that pesky tmp folder

2024-12-11 09:50 UTC, mberacochea commented on main.nf
> +    )
I think what we should do instead, is to modify icefinder.nf and remove the tmp directory there.

```        cd /install/ICEfinder_linux/ && perl ./ICEfinder_local.pl input.list

        if ls -ld result/contig* 2>/dev/null | grep -q .
        then
            cat result/*/*summary.txt > result/icf_concat.summary
            grep 'DR:' result/*/ICE* > result/icf_dr.txt
        else
            echo 'ICEfinder found 0 ICE/IME in assembly... generating dummy files'
            touch result/icf_concat.summary
            touch result/icf_dr.txt
            **rm -rf result/tmp -> I think this is the one** 
        fi
```

2024-12-11 10:00 UTC, Vkale1 commented on main.nf
> +    )
So I tried this I think.. the problem is deleting the bath bound to the container or without specifying the absolute path doesn't work. It deleted essentially the symlink of the staged directory. Hence the use of "readlink" I can try and get the absolute path within this folder. But I just worried if it randomly failed it wouldn't be restartable - hence put it totally external of ice finder, but still running only after ice finder.

If you are able to get this to work though do let me know!

2024-12-11 10:46 UTC, mberacochea commented on main.nf
> +    )
OK. Then another approach would be to copy the results (but that tmp folder) to another place (in Icefinder) and use that to be published (ping me on slack if this doesn't make sense)

2024-12-12 13:45 UTC, Vkale1 commented on main.nf
> +    )
Note here for future reference- spoken in person. This is the best solution for now until we modify the ice finder container.

2024-12-12 13:45 UTC, merged